prefix_dir = ".."
metrics_file = f"{prefix_dir}/router/metrics.log"
rules_file = f"{prefix_dir}/router/rules.log"
metrics_lock_file = metrics_file + ".lock"
rules_lock_file = rules_file + ".lock"
client_cert_dir = f"{prefix_dir}/clientCert"
ca_cert = f"{prefix_dir}/CAcert/CA_cert.pem"
agent_cert = f"{client_cert_dir}/broker_router_cert.pem"
agent_key = f"{client_cert_dir}/broker_router_priv.pem"
host = "fluidos.top-ix.org"
port=5671
requirements_array = []
